### ISSUE TITLE
还可以更仔细一点

### ISSUE THREAD

**Issue by twhy** [zouchenxi/zouchenxi.github.io#1]
如果是第一次做页面，这样已经很不错了，但可以更细致一点，养成习惯。
改善建议
1. 把 logo 设置成 `display: block`，现在 "与世界分享你的知识、经验与见解" 这个二级标题上下间距不对。
2. 没有被选中的 注册 链接，字体颜色是 `#555`。
3. 知乎的输入输入框高度是 47px，你的是 36px，先不要学他用 em 作为单位，用像素 px 把输入框调好。
4. 可以通过 `input::-webkit-input-placeholder { color: #ccc; }` 给 placeholder 设置字体颜色。
5. 下载知乎 App 按钮的字体大小是 14px。
6. 单位先不推荐用 em，用 px 吧。

**Comment by zouchenxi** [comment]
谢谢老师指点~
已经改正。

**Comment by twhy** [comment]
如果都修改好了，就提交吧，然后把这个 issue 关掉。留给你自己关吧。

**Comment by zouchenxi** [comment]
fix #1
